title = "Stefanie Stantcheva"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
relativeURLs = true

[author]
name = "Stefanie Stantcheva"
homepage = "http://leiy.me/"

[params]
title = "Professor of Economics,"
institution = "Harvard University"
logo = "stefanie-stantcheva.jpg" 

