relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Natalia Bermúdez"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Natalia Bermúdez"

[markup] # needed to add html in .md
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Ph.D. Candidate in Economics "
institution = "IRES/LIDAM, UCLOuvain and Department of Economics, UGent"
logo = "P1120239.jpg"
Twitter = "nati_ber"
Email = "natalia.bermudez@uclouvain.be"
Email = "natalia.bermudez@ugent.be"