relativeURLs = true
googleAnalytics = "UA-159072578-1"
title = "Stefanie Stantcheva"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
name = "Stefanie Stantcheva"

[params]
title = "Professor of Economics,"
institution = "Harvard University"
logo = "stefanie-stantcheva-2-compressed-square.jpg"
Twitter = "S_Stantcheva"
Email = "sstantcheva@fas.harvard.edu"